const STRINGS = {
  en: {
    available: "Available",
    elevatedStatus: "Elevated",
    criticalStatus: "Critical",
    blocked: "Blocked",
    stale: "Out of date",
    unavailable: "Unavailable",
    remaining: "remaining",
    resets: "Resets",
    pace: "Pace",
    ahead: "above plan",
    behind: "below plan",
    percentagePoints: "pp",
    credits: "Credits",
    spending: "Spending",
    profile: "Profile",
    noData: "No usage data reported",
    updated: "Updated",
    account: "Account",
    allAccounts: "All accounts",
    unknownWindow: "Usage window",
    fiveHours: "5 hours",
    week: "Week",
    days: "days",
    sections: "Sections",
    advanced: "Advanced",
    documentation: "Documentation",
    thresholds: "Thresholds",
    tokens: "Tokens",
    threads: "Threads",
    overall: "Overall",
    blockerSpend: "Spending limit reached",
    blockerCredits: "Credit limit reached",
    blockerUsage: "Usage limit reached",
    blockerUnknown: "Access currently blocked",
    resetCredits: "Reset credits",
    availableResets: "Available",
    totalEarned: "Total earned",
    nextExpiry: "Next expiry",
    balance: "Balance",
    unlimited: "Unlimited",
    creditState: "Credit state",
    used: "Used",
    limit: "Limit",
    usage: "Usage",
    source: "Scope",
    lifetimeTokens: "Lifetime tokens",
    peakDailyTokens: "Peak daily tokens",
    currentStreak: "Current streak",
    longestStreak: "Longest streak",
    longestTurn: "Longest turn",
    fastMode: "Fast mode",
    totalSkills: "Skill uses",
    uniqueSkills: "Unique skills",
    reasoning: "Reasoning preference",
    reasoningShare: "Reasoning share",
    seconds: "seconds",
    cardTitle: "Title",
    displayMode: "Display mode",
    displayAdaptive: "Adaptive",
    displayCompact: "Compact",
    displayDetailed: "Detailed",
    accountMode: "Account mode",
    accountAuto: "Automatic",
    accountSingle: "One account",
    accountAll: "All accounts",
    selectedAccount: "Fixed account",
    includedAccounts: "Included accounts",
    accountSwitching: "Allow account switching",
    showUnavailable: "Show unavailable limits",
    appearance: "Appearance",
    staleAfter: "Out of date after (minutes)",
    semanticColors: "State colors",
    colorNormal: "Normal",
    colorElevated: "Elevated",
    colorCritical: "Critical",
    colorBlocked: "Blocked",
    colorStale: "Out of date",
    colorMissing: "Unavailable",
    cardRadius: "Card radius",
    panelRadius: "Panel radius",
    spacing: "Spacing",
    resetDefaults: "Reset to defaults",
    sectionLimits: "Limits",
    sectionResets: "Reset times",
    sectionPace: "Pace",
    sectionCredits: "Credits",
    sectionSpending: "Spending",
    sectionProfile: "Profile",
    sectionFooter: "Footer",
  },
  de: {
    available: "Verfügbar",
    elevatedStatus: "Erhöht",
    criticalStatus: "Kritisch",
    blocked: "Blockiert",
    stale: "Veraltet",
    unavailable: "Nicht verfügbar",
    remaining: "verbleibend",
    resets: "Zurücksetzung",
    pace: "Tempo",
    ahead: "über Plan",
    behind: "unter Plan",
    percentagePoints: "Pp",
    credits: "Guthaben",
    spending: "Ausgaben",
    profile: "Profil",
    noData: "Keine Nutzungsdaten gemeldet",
    updated: "Aktualisiert",
    account: "Konto",
    allAccounts: "Alle Konten",
    unknownWindow: "Nutzungsfenster",
    fiveHours: "5 Stunden",
    week: "Woche",
    days: "Tage",
    sections: "Bereiche",
    advanced: "Erweitert",
    documentation: "Dokumentation",
    thresholds: "Schwellenwerte",
    tokens: "Token",
    threads: "Unterhaltungen",
    overall: "Gesamt",
    blockerSpend: "Ausgabenlimit erreicht",
    blockerCredits: "Guthabenlimit erreicht",
    blockerUsage: "Nutzungslimit erreicht",
    blockerUnknown: "Zugriff derzeit blockiert",
    resetCredits: "Reset-Guthaben",
    availableResets: "Verfügbar",
    totalEarned: "Insgesamt erhalten",
    nextExpiry: "Nächster Verfall",
    balance: "Guthaben",
    unlimited: "Unbegrenzt",
    creditState: "Guthabenstatus",
    used: "Verbraucht",
    limit: "Limit",
    usage: "Nutzung",
    source: "Geltungsbereich",
    lifetimeTokens: "Token gesamt",
    peakDailyTokens: "Höchster Tageswert",
    currentStreak: "Aktuelle Serie",
    longestStreak: "Längste Serie",
    longestTurn: "Längster Durchlauf",
    fastMode: "Fast Mode",
    totalSkills: "Skill-Nutzungen",
    uniqueSkills: "Verschiedene Skills",
    reasoning: "Reasoning-Präferenz",
    reasoningShare: "Reasoning-Anteil",
    seconds: "Sekunden",
    cardTitle: "Titel",
    displayMode: "Anzeigemodus",
    displayAdaptive: "Adaptiv",
    displayCompact: "Kompakt",
    displayDetailed: "Detailliert",
    accountMode: "Kontomodus",
    accountAuto: "Automatisch",
    accountSingle: "Ein Konto",
    accountAll: "Alle Konten",
    selectedAccount: "Festes Konto",
    includedAccounts: "Einbezogene Konten",
    accountSwitching: "Kontowechsel erlauben",
    showUnavailable: "Nicht verfügbare Limits anzeigen",
    appearance: "Darstellung",
    staleAfter: "Veraltet nach (Minuten)",
    semanticColors: "Zustandsfarben",
    colorNormal: "Normal",
    colorElevated: "Erhöht",
    colorCritical: "Kritisch",
    colorBlocked: "Blockiert",
    colorStale: "Veraltet",
    colorMissing: "Nicht verfügbar",
    cardRadius: "Kartenradius",
    panelRadius: "Panelradius",
    spacing: "Abstand",
    resetDefaults: "Auf Standard zurücksetzen",
    sectionLimits: "Limits",
    sectionResets: "Zurücksetzungen",
    sectionPace: "Tempo",
    sectionCredits: "Guthaben",
    sectionSpending: "Ausgaben",
    sectionProfile: "Profil",
    sectionFooter: "Fußzeile",
  },
} as const;

export type TranslationKey = keyof (typeof STRINGS)["en"];

export function localize(language: string | undefined, key: TranslationKey): string {
  return STRINGS[language?.toLowerCase().startsWith("de") ? "de" : "en"][key];
}
