const STRINGS = {
  en: {
    available: "Available",
    blocked: "Blocked",
    stale: "Out of date",
    unavailable: "Unavailable",
    remaining: "remaining",
    resets: "Resets",
    pace: "Pace",
    ahead: "ahead of time",
    behind: "below time",
    credits: "Credits",
    spending: "Spending",
    profile: "Profile",
    noData: "No usage data reported",
    updated: "Updated",
    account: "Account",
    allAccounts: "All accounts",
    unknownWindow: "Usage window",
    fiveHours: "5 hours",
    week: "Week",
    days: "days",
    sections: "Sections",
    advanced: "Advanced",
    documentation: "Documentation",
    thresholds: "Thresholds",
    tokens: "Tokens",
    threads: "Threads",
    cardTitle: "Title",
    displayMode: "Display mode",
    accountMode: "Account mode",
    selectedAccount: "Fixed account",
    accountSwitching: "Allow account switching",
    showUnavailable: "Show unavailable limits",
    appearance: "Appearance",
    resetDefaults: "Reset to defaults",
    sectionLimits: "Limits",
    sectionResets: "Reset times",
    sectionPace: "Pace",
    sectionCredits: "Credits",
    sectionSpending: "Spending",
    sectionProfile: "Profile",
    sectionFooter: "Footer",
  },
  de: {
    available: "Verfügbar",
    blocked: "Blockiert",
    stale: "Veraltet",
    unavailable: "Nicht verfügbar",
    remaining: "verbleibend",
    resets: "Zurücksetzung",
    pace: "Tempo",
    ahead: "über Zeitfortschritt",
    behind: "unter Zeitfortschritt",
    credits: "Guthaben",
    spending: "Ausgaben",
    profile: "Profil",
    noData: "Keine Nutzungsdaten gemeldet",
    updated: "Aktualisiert",
    account: "Konto",
    allAccounts: "Alle Konten",
    unknownWindow: "Nutzungsfenster",
    fiveHours: "5 Stunden",
    week: "Woche",
    days: "Tage",
    sections: "Bereiche",
    advanced: "Erweitert",
    documentation: "Dokumentation",
    thresholds: "Schwellenwerte",
    tokens: "Token",
    threads: "Unterhaltungen",
    cardTitle: "Titel",
    displayMode: "Anzeigemodus",
    accountMode: "Kontomodus",
    selectedAccount: "Festes Konto",
    accountSwitching: "Kontowechsel erlauben",
    showUnavailable: "Nicht verfügbare Limits anzeigen",
    appearance: "Darstellung",
    resetDefaults: "Auf Standard zurücksetzen",
    sectionLimits: "Limits",
    sectionResets: "Zurücksetzungen",
    sectionPace: "Tempo",
    sectionCredits: "Guthaben",
    sectionSpending: "Ausgaben",
    sectionProfile: "Profil",
    sectionFooter: "Fußzeile",
  },
} as const;

export type TranslationKey = keyof (typeof STRINGS)["en"];

export function localize(language: string | undefined, key: TranslationKey): string {
  return STRINGS[language?.toLowerCase().startsWith("de") ? "de" : "en"][key];
}
