export const STRINGS = {
  en: {
    available: "Available",
    blocked: "Blocked",
    unavailable: "Unavailable",
    remaining: "remaining",
    usedInline: "used",
    resets: "Resets",
    pace: "Pace",
    ahead: "above plan",
    behind: "below plan",
    percentagePoints: "pp",
    credits: "Credits",
    spending: "Spending",
    profile: "Profile",
    noData: "No usage data reported",
    updated: "Updated",
    account: "Account",
    allAccounts: "All accounts",
    unknownWindow: "Usage window",
    fiveHours: "5 hours",
    week: "Week",
    days: "days",
    sections: "Sections",
    advanced: "Advanced",
    documentation: "Documentation",
    thresholds: "Thresholds",
    tokens: "Tokens",
    threads: "Threads",
    overall: "Overall",
    blockerSpend: "Spending limit reached",
    blockerCredits: "Credit limit reached",
    blockerUsage: "Usage limit reached",
    blockerUnknown: "Access currently blocked",
    resetCredits: "Reset credits",
    availableResets: "Available",
    totalEarned: "Total earned",
    nextExpiry: "Next expiry",
    balance: "Balance",
    unlimited: "Unlimited",
    creditState: "Credit state",
    used: "Used",
    limit: "Limit",
    usage: "Usage",
    source: "Scope",
    lifetimeTokens: "Lifetime tokens",
    peakDailyTokens: "Peak daily tokens",
    currentStreak: "Current streak",
    longestStreak: "Longest streak",
    longestTurn: "Longest turn",
    fastMode: "Fast mode",
    totalSkills: "Skill uses",
    uniqueSkills: "Unique skills",
    reasoning: "Reasoning preference",
    reasoningShare: "Reasoning share",
    seconds: "seconds",
    cardTitle: "Title",
    compactMode: "Start collapsed",
    accountMode: "Account mode",
    accountAuto: "Automatic",
    accountSingle: "One account",
    accountAll: "All accounts",
    selectedAccount: "Fixed account",
    includedAccounts: "Included accounts",
    accountSwitching: "Allow account switching",
    showUnavailable: "Show unavailable limits",
    appearance: "Appearance",
    staleAfter: "Out of date after (minutes)",
    semanticColors: "State colors",
    colorOk: "Healthy",
    colorWarning: "Warning",
    colorCritical: "Critical",
    colorBlocked: "Blocked",
    colorUnknown: "Unavailable",
    cardRadius: "Card radius",
    spacing: "Spacing",
    resetDefaults: "Reset to defaults",
    sectionLimits: "Limits",
    sectionAdditionalLimits: "Additional limits",
    sectionResets: "Reset times",
    sectionPace: "Pace",
    sectionAccount: "Account",
    sectionCredits: "Credits",
    sectionSpending: "Spending",
    sectionProfile: "Profile",
    sectionFooter: "Footer",
    thresholdWarning: "Warning",
    // severity chip copy
    severityUnknown: "Data unavailable",
    severityOk: "Healthy",
    severityWarning: "Low usage remaining",
    severityCritical: "Critically low usage remaining",
    severityBlocked: "Limit reached",
    // freshness
    dataMayBeOutdated: "Data may be outdated",
    // most-constrained callout
    mostConstrainedTightest: "{limit} is currently your tightest constraint.",
    mostConstrainedLowRemaining: "{limit} has only {percent}% remaining.",
    mostConstrainedBlockedUsage: "Codex usage is currently blocked by your {limit}.",
    mostConstrainedBlockedSpend: "Usage is currently blocked by your spending limit.",
    mostConstrainedBlockedCredits: "Usage is currently blocked by your credit limit.",
    mostConstrainedBlockedUnknown: "Codex usage is currently unavailable.",
    // relative reset time
    resetsImminently: "Resets shortly",
    resetsInMinutes: "Resets in {minutes} min",
    resetsInHours: "Resets in {hours}h",
    resetsInHoursMinutes: "Resets in {hours}h {minutes}m",
    resetsInDays: "Resets in {days}d",
    resetsInDaysHours: "Resets in {days}d {hours}h",
    // details toggle
    showDetails: "Show details",
    hideDetails: "Hide details",
    // account details
    planLabel: "Plan",
    workspace: "Workspace",
    accountId: "Account ID",
    // friendlier credits/spend copy
    unlimitedCredits: "Unlimited credits",
    creditsAvailableAmount: "{amount} available",
    resetCreditsAvailable: "{count} reset credits available",
    expiresOn: "Expires {date}",
  },
  de: {
    available: "Verfügbar",
    blocked: "Blockiert",
    unavailable: "Nicht verfügbar",
    remaining: "verbleibend",
    usedInline: "verbraucht",
    resets: "Zurücksetzung",
    pace: "Tempo",
    ahead: "über Plan",
    behind: "unter Plan",
    percentagePoints: "Pp",
    credits: "Guthaben",
    spending: "Ausgaben",
    profile: "Profil",
    noData: "Keine Nutzungsdaten gemeldet",
    updated: "Aktualisiert",
    account: "Konto",
    allAccounts: "Alle Konten",
    unknownWindow: "Nutzungsfenster",
    fiveHours: "5 Stunden",
    week: "Woche",
    days: "Tage",
    sections: "Bereiche",
    advanced: "Erweitert",
    documentation: "Dokumentation",
    thresholds: "Schwellenwerte",
    tokens: "Token",
    threads: "Unterhaltungen",
    overall: "Gesamt",
    blockerSpend: "Ausgabenlimit erreicht",
    blockerCredits: "Guthabenlimit erreicht",
    blockerUsage: "Nutzungslimit erreicht",
    blockerUnknown: "Zugriff derzeit blockiert",
    resetCredits: "Reset-Guthaben",
    availableResets: "Verfügbar",
    totalEarned: "Insgesamt erhalten",
    nextExpiry: "Nächster Verfall",
    balance: "Guthaben",
    unlimited: "Unbegrenzt",
    creditState: "Guthabenstatus",
    used: "Verbraucht",
    limit: "Limit",
    usage: "Nutzung",
    source: "Geltungsbereich",
    lifetimeTokens: "Token gesamt",
    peakDailyTokens: "Höchster Tageswert",
    currentStreak: "Aktuelle Serie",
    longestStreak: "Längste Serie",
    longestTurn: "Längster Durchlauf",
    fastMode: "Fast Mode",
    totalSkills: "Skill-Nutzungen",
    uniqueSkills: "Verschiedene Skills",
    reasoning: "Reasoning-Präferenz",
    reasoningShare: "Reasoning-Anteil",
    seconds: "Sekunden",
    cardTitle: "Titel",
    compactMode: "Eingeklappt starten",
    accountMode: "Kontomodus",
    accountAuto: "Automatisch",
    accountSingle: "Ein Konto",
    accountAll: "Alle Konten",
    selectedAccount: "Festes Konto",
    includedAccounts: "Einbezogene Konten",
    accountSwitching: "Kontowechsel erlauben",
    showUnavailable: "Nicht verfügbare Limits anzeigen",
    appearance: "Darstellung",
    staleAfter: "Veraltet nach (Minuten)",
    semanticColors: "Zustandsfarben",
    colorOk: "Gesund",
    colorWarning: "Warnung",
    colorCritical: "Kritisch",
    colorBlocked: "Blockiert",
    colorUnknown: "Nicht verfügbar",
    cardRadius: "Kartenradius",
    spacing: "Abstand",
    resetDefaults: "Auf Standard zurücksetzen",
    sectionLimits: "Limits",
    sectionAdditionalLimits: "Zusätzliche Limits",
    sectionResets: "Zurücksetzungen",
    sectionPace: "Tempo",
    sectionAccount: "Konto",
    sectionCredits: "Guthaben",
    sectionSpending: "Ausgaben",
    sectionProfile: "Profil",
    sectionFooter: "Fußzeile",
    thresholdWarning: "Warnung",
    // severity chip copy
    severityUnknown: "Daten nicht verfügbar",
    severityOk: "Gesund",
    severityWarning: "Wenig Nutzung übrig",
    severityCritical: "Kritisch wenig Nutzung übrig",
    severityBlocked: "Limit erreicht",
    // freshness
    dataMayBeOutdated: "Daten könnten veraltet sein",
    // most-constrained callout
    mostConstrainedTightest: "{limit} ist derzeit dein engstes Limit.",
    mostConstrainedLowRemaining: "{limit} hat nur noch {percent}% übrig.",
    mostConstrainedBlockedUsage: "Die Codex-Nutzung wird derzeit durch dein {limit} blockiert.",
    mostConstrainedBlockedSpend: "Die Nutzung wird derzeit durch dein Ausgabenlimit blockiert.",
    mostConstrainedBlockedCredits: "Die Nutzung wird derzeit durch dein Guthabenlimit blockiert.",
    mostConstrainedBlockedUnknown: "Die Codex-Nutzung ist derzeit nicht verfügbar.",
    // relative reset time
    resetsImminently: "Setzt sich gleich zurück",
    resetsInMinutes: "Setzt sich in {minutes} Min. zurück",
    resetsInHours: "Setzt sich in {hours}h zurück",
    resetsInHoursMinutes: "Setzt sich in {hours}h {minutes}m zurück",
    resetsInDays: "Setzt sich in {days}d zurück",
    resetsInDaysHours: "Setzt sich in {days}d {hours}h zurück",
    // details toggle
    showDetails: "Details anzeigen",
    hideDetails: "Details ausblenden",
    // account details
    planLabel: "Plan",
    workspace: "Workspace",
    accountId: "Konto-ID",
    // friendlier credits/spend copy
    unlimitedCredits: "Unbegrenztes Guthaben",
    creditsAvailableAmount: "{amount} verfügbar",
    resetCreditsAvailable: "{count} Reset-Guthaben verfügbar",
    expiresOn: "Läuft ab am {date}",
  },
} as const;

export type TranslationKey = keyof (typeof STRINGS)["en"];

export function localize(
  language: string | undefined,
  key: TranslationKey,
  values?: Record<string, string | number>,
): string {
  const template = STRINGS[language?.toLowerCase().startsWith("de") ? "de" : "en"][key];
  if (!values) return template;
  return template.replace(/\{(\w+)\}/g, (match, token: string) =>
    token in values ? String(values[token]) : match,
  );
}
